export const texts = [
    "small blue bird singing happily sweet melody morning sunshine warm gentle breeze blowing softly through trees tall green leaves dancing gracefully in wind happy little creature chirping merrily",
    "soft white clouds floating lazily across sky vast expanse of blue endless possibilities stretching out horizon clear and bright day perfect for adventure exploring new places meeting interesting people making lifelong memories",
    "cozy little cottage nestled among colorful flowers vibrant garden filled with life buzzing bees collecting pollen butterflies fluttering gracefully from flower to flower gentle hum of nature peaceful and serene atmosphere perfect place to relax and unwind",
    "ancient oak tree standing strong against time weathered bark tells stories of seasons past leaves rustling in autumn wind whispering secrets of nature roots firmly planted in earth providing shelter for creatures big and small",
    "children laughing joyfully playing hide and seek running through fields of tall grass chasing butterflies carefree and innocent moments of pure happiness simple pleasures of childhood filled with wonder and imagination",
    "golden sunset painting sky with vibrant colors fiery hues reflecting on calm water gentle waves lapping softly against shore peaceful silence broken only by sound of seagulls calling distant horizon disappearing into darkness",
    "busy city streets filled with energy people rushing to and fro honking cars and sirens wailing constant movement and noise never ending stream of humanity diverse cultures and backgrounds melting pot of life",
    "snowflakes falling gently from sky blanketing world in white everything covered in soft layer of white magic children building snowmen and having snowball fights cozy fireplace crackling warmly inside perfect winter wonderland",
    "delicious aroma of freshly baked bread filling kitchen warm and inviting atmosphere family gathered around table sharing stories and laughter simple joys of life cherished moments of togetherness creating lasting memories",
    "starry night sky filled with twinkling lights countless stars shining brightly mysterious and magical universe endless possibilities and questions waiting to be explored wonder and awe inspiring sense of peace",
    "old wooden bridge crossing over rushing river strong and sturdy structure weathered by time and elements connecting two sides of the river symbol of connection and passage of time",
    "colorful hot air balloon floating gracefully through sky breathtaking view from above world looking small and insignificant sense of freedom and adventure soaring high above the clouds",
    "wildflowers blooming in meadow vibrant colors filling the air with sweet fragrance bees buzzing happily collecting pollen butterflies fluttering gracefully from flower to flower peaceful and serene atmosphere",
    "ancient ruins covered in moss and vines remnants of a civilization long gone stories of the past etched in stone mysteries waiting to be uncovered exploring the unknown",
    "raindrops falling gently on windowpane creating a soothing rhythm world outside transformed into a blurry canvas soft and quiet atmosphere perfect for reading and relaxation"
];